### ISSUE TITLE
  IDOCAdapterPrefix:

### ISSUE THREAD

**Issue by sehunjung** [aws-samples/aws-cloudformation-apigw-sap-idocs#3]
hi......
 UserPoolClient  & UserPool are  necessary for IDOCAdapterPrefix.
I have deployed with SAM so i cannot create  UserPoolClient  & UserPool.
plz let me know. how to config prefix without  UserPoolClient  & UserPool.

thanks. best regards.
===================

  IDOCAdapterPrefix:
    Value: !Join
    - ""
    - - "/latest?"
      - "upid="
      - !Ref UserPool   <- UserPool:
      - "&cid="
      - !Ref UserPoolClient <- UserPoolClient:
      - "&bn="
      - !Ref IDOCBucket <-IDOCBucket:

**Comment by frumania** [comment]
Added instructions on deploment. SAM is not supported.
