### ISSUE TITLE
An error occurred (IllegalLocationConstraintException)

### ISSUE THREAD

**Issue by sehunjung** [aws-samples/aws-cloudformation-apigw-sap-idocs#4]
i faced "An error occurred (IllegalLocationConstraintException)"

Default region name [None]: us-west-2 => is OK..
but ap-northeast-2 give me error..

do i have to something others??
i want to set up my new id for ap-northeast-2 region...

**Comment by kumarrk21** [comment]
Are you facing this issue when deploying the stack using deploy.sh script or you are receiving this error when the cloudformation stack is executed

**Comment by kumarrk21** [comment]
This was an issue in the the script. I updated the script to use 'mb' instead of 'create-bucket'. Please pull the latest version and redeploy. That should take care of the IllegalLocationConstraintException. Closing this issue. Please reopen if you face this again.
